
export enum ErrorCode {
    GAME_FOUND = 10,
    PLAYER_JOINED = 20,
    PLAYER_LEFT = 30,
    GAME_STARTED = 40,
    GAME_COUNTDOWN = 41,
    GAME_OVER = 42,
    SCORE_UPDATE = 43,
    LOBBY_CONNECT = 50,
    LOBBY_UPDATE = 51,
  }